### PR TITLE
UPDATES!!

### PR DESCRIPTION
**Pull request by AKASGaming**
# • Updated from .NET 4.5 to .NET 4.8
# • Updated other Packages
# • Supports adding multiple files at once to Trailers and Prerolls
# • Fixed Time and Date
# • Moved Logs for bigger screens
# • Added Placeholder options for Randomized Prerolls and Specified amount of Prerolls
(Someone else needs to implement these features 😜)
# • Movies/Feature Supports more formats
# • Proper Folder Picker

### CODE REVIEW

**Review by wmandra — COMMENTED** [review]
Commit will not be accepted even if fully implemented. Randomization of preroll is not a desired feature.

**Review by wmandra — CHANGES_REQUESTED** [review]
Changes to GeneralSettings.xaml should be removed.

New icons should be in Resources\Icons path not Windows.
Several of the icons added already exist in the project.

**Comment by AKASGaming** [comment]
1. What if other users would like this feature? I'm already working on the randomizer part right now
2. I have no clue why VS moved/duplicated those

**Review by wmandra — COMMENTED** [review]
Need to separate version update changes from feature changes with separate commits.

Changes to DigitalHomeCinemaManager/Controls/Settings/GeneralSettings.xaml are unnecessary.

Changes to DigitalHomeCinemaManager/Controls/Settings/GeneralSettings.xaml.cs are generally ok but should continue to use Environment.SpecicalFolder.MyVideos for exceptions. Again, randomize function should be removed.

Movie filter should remain .mkv only.

Changes of date from lowercase to uppercase will not be merged for style reasons. CA1308 was explicitly disabled for this reason.

No reason for clockTimer to have 1s resolution. This change unnecessarily increases calls to OnTimerElapsed handler.

PlaylistSelectionWindow should not support multi-select by default. Instead a Multiselect property should be added to the PlaylistSelectionWindow class.  Multiselect ok for Preroll, Trailers, and Commercials but not Feature.

Margin change to Dolby logo unnecessary.

Combination of time hour/minute ok, but time display should remain hh:mm only.

I don't understand the rationale for the log output move.

**Comment by wmandra** [comment]
> 1. What if other users would like this feature? I'm already working on the randomizer part right now
> 2. I have no clue why VS moved/duplicated those

It doesn't really fit the use case at least not for Preroll or Commercials. 

I do think randomization or number limit might fit for Trailers, but even then I'm not convinced of the necessity.

**Comment by AKASGaming** [comment]
> I do think randomization or number limit might fit for Trailers, but even then I'm not convinced of the necessity.

Yeah, that's a typo on my end, it's meant for the trailers.


> It doesn't really fit the use case

This would be used when your playlist contains multiple trailers, so it'll automatically shuffle them when added.


> Margin change to Dolby logo unnecessary

That was an accident and I forgot to move it back


> log output move

It doesn't fit on small screens, but on large screens is easy to see


> Multiselect ok for Preroll, Trailers, and Commercials but not Feature

Did you actually test this feature yourself? It only does this on Trailers and Prerolls, not Commercials or the Feature


> Changes to DigitalHomeCinemaManager/Controls/Settings/GeneralSettings.xaml.cs are generally ok but should continue to use Environment.SpecicalFolder.MyVideos for exceptions

I tried this, but it ended up making the folder dialog buggy


> Movie filter should remain .mkv only

Why? Most of the movies I have are .mp4 and .mkv so only a select few would actually be playable


> Changes to DigitalHomeCinemaManager/Controls/Settings/GeneralSettings.xaml are unnecessary

Would clearing the playlist be a bad thing? What if a user wants a completely different playlist? Then they'd have to manually remove everything they have on it already. And this also includes tooltips to help better understand the buttons

> No reason for clockTimer to have 1s resolution. This change unnecessarily increases calls to OnTimerElapsed handler.

This is for the clock display

**Comment by AKASGaming** [comment]
You're not gonna accept the changes I've made anyways ¯\_(ツ)_/¯

**Pull request closed without merging**
